#!/bin/sh
#
# ACME init
#

# Power on the GPIO1 pin for each probe
# USB and JACK probes has their SW_EN on it
for GPIO in 489 491 493 495 497 499 501 503
do
	echo $GPIO > /sys/class/gpio/export
	echo high > /sys/class/gpio/gpio$GPIO/direction
done
