#!/bin/sh
#
# ACME init
#
for probe in 0 1 2 3 4 5 6 7
do
  if [ -f /sys/bus/i2c/devices/4-004$probe/iio:device*/in_shunt_resistor ]
  then
	rshunt=`dut-dump-probe -b 4 -r $probe`
	echo $rshunt > /sys/bus/i2c/devices/4-004$probe/iio:device*/in_shunt_resistor
  fi
done
