#!/bin/sh
#
# ACME init
#
for probe in 0 1 2 3 4 5 6 7
do
  if [ -f /sys/bus/i2c/devices/1-004$probe/iio:device*/in_shunt_resistor ]
  then
	iiodevice=`ls /sys/bus/i2c/devices/1-004$probe/iio:device*/in_shunt_resistor`
	rshunt=`dut-dump-probe -b 1 -r $((probe+1))`
	echo $rshunt > $iiodevice
  fi
done
